-- MySQL Script generated by MySQL Workbench
-- Thu Jun  2 11:49:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `client_id` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `zipCode` INT NOT NULL,
  `phoneNb` INT NOT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `client_id_UNIQUE` (`client_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = Default;


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `idManager` INT NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idManager`),
  UNIQUE INDEX `idManager_UNIQUE` (`idManager` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant` (
  `idRestaurant` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `zipCode` INT NOT NULL,
  `phoneNb` INT NOT NULL,
  `idManager` INT NOT NULL,
  PRIMARY KEY (`idRestaurant`),
  UNIQUE INDEX `idRestaurant_UNIQUE` (`idRestaurant` ASC) VISIBLE,
  UNIQUE INDEX `idManager_UNIQUE` (`idManager` ASC) VISIBLE,
  CONSTRAINT `idManager`
    FOREIGN KEY (`idManager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeliveryGuy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DeliveryGuy` (
  `idDeliveryGuy` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `gpsPosition` VARCHAR(255) NOT NULL DEFAULT '48,87228° N, 2,33306° E',
  PRIMARY KEY (`idDeliveryGuy`),
  UNIQUE INDEX `idDeliveryGuy_UNIQUE` (`idDeliveryGuy` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`OrderStatut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderStatut` (
  `idOrderStatut` INT NOT NULL,
  `OrderStatut` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idOrderStatut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PizzaGuy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PizzaGuy` (
  `idPizzaGuy` INT NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPizzaGuy`),
  UNIQUE INDEX `idPizzaGuy_UNIQUE` (`idPizzaGuy` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idOrder` INT NOT NULL,
  `client_id` INT NOT NULL,
  `idRestaurant` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT 20220501,
  `idOrderStatut` INT NOT NULL,
  `alreadyPaid` TINYINT NOT NULL,
  `priceHT` DOUBLE NOT NULL,
  `taxe` DOUBLE NOT NULL,
  `needDelivery` TINYINT NOT NULL,
  `idDeliveryGuy` INT NOT NULL,
  `pickUpDate` DATETIME NOT NULL DEFAULT 20220501,
  `deliveryDate` DATETIME NOT NULL DEFAULT 20220501,
  `idPizzaGuy` INT NOT NULL DEFAULT 0000000,
  PRIMARY KEY (`idOrder`),
  UNIQUE INDEX `idOrder_UNIQUE` (`idOrder` ASC) VISIBLE,
  INDEX `client_id_idx` (`client_id` ASC) VISIBLE,
  INDEX `idRestaurant_idx` (`idRestaurant` ASC) VISIBLE,
  INDEX `idDeliveryGuy_idx` (`idDeliveryGuy` ASC) VISIBLE,
  INDEX `idOrderStatut_idx` (`idOrderStatut` ASC) VISIBLE,
  INDEX `idPizzaGuy_idx` (`idPizzaGuy` ASC) VISIBLE,
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`Client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRestaurant`
    FOREIGN KEY (`idRestaurant`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDeliveryGuy`
    FOREIGN KEY (`idDeliveryGuy`)
    REFERENCES `mydb`.`DeliveryGuy` (`idDeliveryGuy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idOrderStatut`
    FOREIGN KEY (`idOrderStatut`)
    REFERENCES `mydb`.`OrderStatut` (`idOrderStatut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPizzaGuy`
    FOREIGN KEY (`idPizzaGuy`)
    REFERENCES `mydb`.`PizzaGuy` (`idPizzaGuy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `idPizza` INT NOT NULL,
  `name` VARCHAR(55) NOT NULL,
  `size` INT NOT NULL,
  `idRestaurant` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `recipe` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPizza`),
  UNIQUE INDEX `idPizza_UNIQUE` (`idPizza` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredient` (
  `idIngredient` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `priceHT` DOUBLE NOT NULL,
  `expirationDate` DATE NOT NULL,
  PRIMARY KEY (`idIngredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `idSupplier` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `zipCode` INT NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `phoneNb` INT NOT NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredient_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredient_Order` (
  `idIngredient_Order` INT NOT NULL,
  `Manager` INT NOT NULL,
  `OrderStatut` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`idIngredient_Order`),
  INDEX `idManager_idx` (`Manager` ASC) VISIBLE,
  INDEX `idOrderStatut_idx` (`OrderStatut` ASC) VISIBLE,
  CONSTRAINT `Manager`
    FOREIGN KEY (`Manager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrderStatut`
    FOREIGN KEY (`OrderStatut`)
    REFERENCES `mydb`.`OrderStatut` (`idOrderStatut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assoc_Ingredient_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assoc_Ingredient_Order` (
  `idIngredient_Order` INT NOT NULL,
  `ingredient` INT NOT NULL,
  `idSupplier` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `idSupplier_idx` (`idSupplier` ASC) VISIBLE,
  INDEX `idIngredient_Order_idx` (`idIngredient_Order` ASC) VISIBLE,
  INDEX `ingredient_idx` (`ingredient` ASC) VISIBLE,
  CONSTRAINT `idIngredient_Order`
    FOREIGN KEY (`idIngredient_Order`)
    REFERENCES `mydb`.`Ingredient_Order` (`idIngredient_Order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSupplier`
    FOREIGN KEY (`idSupplier`)
    REFERENCES `mydb`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ingredient`
    FOREIGN KEY (`ingredient`)
    REFERENCES `mydb`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assoc_Menu_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assoc_Menu_Order` (
  `idOrder` INT NOT NULL,
  `idPizza` INT NOT NULL,
  `quantity` INT NULL,
  INDEX `idOrder_idx` (`idOrder` ASC) VISIBLE,
  INDEX `idPizza_idx` (`idPizza` ASC) VISIBLE,
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPizza`
    FOREIGN KEY (`idPizza`)
    REFERENCES `mydb`.`Menu` (`idPizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assoc_Pizza_Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assoc_Pizza_Ingredient` (
  `Pizza` INT NOT NULL,
  `Ingredient_` INT NOT NULL,
  INDEX `idPizza_idx` (`Pizza` ASC) VISIBLE,
  INDEX `Ingredient_idx` (`Ingredient_` ASC) VISIBLE,
  CONSTRAINT `Pizza`
    FOREIGN KEY (`Pizza`)
    REFERENCES `mydb`.`Menu` (`idPizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ingredient_`
    FOREIGN KEY (`Ingredient_`)
    REFERENCES `mydb`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stock` (
  `Ingredient_ID` INT NOT NULL,
  `Restaurant_ID` INT NOT NULL,
  `quantityStock` INT NOT NULL,
  INDEX `Ingredient_ID_idx` (`Ingredient_ID` ASC) VISIBLE,
  INDEX `Restaurant_ID_idx` (`Restaurant_ID` ASC) VISIBLE,
  CONSTRAINT `Ingredient_ID`
    FOREIGN KEY (`Ingredient_ID`)
    REFERENCES `mydb`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Restaurant_ID`
    FOREIGN KEY (`Restaurant_ID`)
    REFERENCES `mydb`.`Restaurant` (`idRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
